/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QA.estudos.app;



public class App {
    public String gretting() {
        return "Hello word";
    }

    public static void main(String[] args) {
        System.out.println(new App().gretting());
    }
}