/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QA.estudos.app;

class MessageUtils {

    public static String getMessage() {
        return "Hello      World!";
    }
}
