/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QA.estudos.app;

import org.junit.Test;


class MessageUtilsTest {
    @Test
    void testGetMessage() {
        assertEquals("Hello World!", MessageUtils.getMessage());
    }

    private void assertEquals(String s, String message) {
    }
}
